-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE mw_settings (
  s_dbname VARCHAR(64) NOT NULL,
  s_settings JSONB DEFAULT NULL,
  s_extensions JSONB DEFAULT NULL,
  PRIMARY KEY(s_dbname)
);

CREATE INDEX s_dbname ON mw_settings (s_dbname);


CREATE TABLE mw_permissions (
  perm_dbname VARCHAR(64) NOT NULL,
  perm_group VARCHAR(64) NOT NULL,
  perm_permissions JSONB NOT NULL,
  perm_addgroups JSONB NOT NULL,
  perm_removegroups JSONB NOT NULL,
  perm_addgroupstoself JSONB NOT NULL,
  perm_removegroupsfromself JSONB NOT NULL,
  perm_autopromote JSONB DEFAULT NULL
);

CREATE UNIQUE INDEX uniqueperm ON mw_permissions (perm_dbname, perm_group);

CREATE INDEX perm_dbname ON mw_permissions (perm_dbname);

CREATE INDEX perm_group ON mw_permissions (perm_group);


CREATE TABLE mw_namespaces (
  ns_dbname VARCHAR(64) NOT NULL,
  ns_namespace_id BIGINT NOT NULL,
  ns_namespace_name VARCHAR(128) NOT NULL,
  ns_searchable SMALLINT NOT NULL,
  ns_subpages SMALLINT NOT NULL,
  ns_content SMALLINT NOT NULL,
  ns_content_model VARCHAR(32) NOT NULL,
  ns_protection VARCHAR(32) NOT NULL,
  ns_aliases JSONB NOT NULL,
  ns_core INT DEFAULT 0 NOT NULL,
  ns_additional JSONB NOT NULL
);

CREATE UNIQUE INDEX uniquens ON mw_namespaces (ns_dbname, ns_namespace_id);

CREATE INDEX ns_dbname ON mw_namespaces (ns_dbname);
