-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mw_settings (
  s_dbname VARCHAR(64) NOT NULL,
  s_settings CLOB DEFAULT NULL,
  s_extensions CLOB DEFAULT NULL,
  PRIMARY KEY(s_dbname)
);

CREATE INDEX s_dbname ON /*_*/mw_settings (s_dbname);


CREATE TABLE /*_*/mw_permissions (
  perm_dbname VARCHAR(64) NOT NULL,
  perm_group VARCHAR(64) NOT NULL,
  perm_permissions CLOB NOT NULL,
  perm_addgroups CLOB NOT NULL,
  perm_removegroups CLOB NOT NULL,
  perm_addgroupstoself CLOB NOT NULL,
  perm_removegroupsfromself CLOB NOT NULL,
  perm_autopromote CLOB DEFAULT NULL
);

CREATE UNIQUE INDEX uniqueperm ON /*_*/mw_permissions (perm_dbname, perm_group);

CREATE INDEX perm_dbname ON /*_*/mw_permissions (perm_dbname);

CREATE INDEX perm_group ON /*_*/mw_permissions (perm_group);


CREATE TABLE /*_*/mw_namespaces (
  ns_dbname VARCHAR(64) NOT NULL,
  ns_namespace_id BIGINT UNSIGNED NOT NULL,
  ns_namespace_name VARCHAR(128) NOT NULL,
  ns_searchable SMALLINT NOT NULL,
  ns_subpages SMALLINT NOT NULL,
  ns_content SMALLINT NOT NULL,
  ns_content_model VARCHAR(32) NOT NULL,
  ns_protection VARCHAR(32) NOT NULL,
  ns_aliases CLOB NOT NULL,
  ns_core INTEGER DEFAULT 0 NOT NULL,
  ns_additional CLOB NOT NULL
);

CREATE UNIQUE INDEX uniquens ON /*_*/mw_namespaces (ns_dbname, ns_namespace_id);

CREATE INDEX ns_dbname ON /*_*/mw_namespaces (ns_dbname);
