-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mw_settings (
  s_dbname VARCHAR(64) NOT NULL,
  s_settings JSON DEFAULT NULL,
  s_extensions JSON DEFAULT NULL,
  INDEX s_dbname (s_dbname),
  PRIMARY KEY(s_dbname)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/mw_permissions (
  perm_dbname VARCHAR(64) NOT NULL,
  perm_group VARCHAR(64) NOT NULL,
  perm_permissions JSON NOT NULL,
  perm_addgroups JSON NOT NULL,
  perm_removegroups JSON NOT NULL,
  perm_addgroupstoself JSON NOT NULL,
  perm_removegroupsfromself JSON NOT NULL,
  perm_autopromote JSON DEFAULT NULL,
  UNIQUE INDEX uniqueperm (perm_dbname, perm_group),
  INDEX perm_dbname (perm_dbname),
  INDEX perm_group (perm_group)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/mw_namespaces (
  ns_dbname VARCHAR(64) NOT NULL,
  ns_namespace_id BIGINT UNSIGNED NOT NULL,
  ns_namespace_name VARCHAR(128) NOT NULL,
  ns_searchable TINYINT NOT NULL,
  ns_subpages TINYINT NOT NULL,
  ns_content TINYINT NOT NULL,
  ns_content_model VARCHAR(32) NOT NULL,
  ns_protection VARCHAR(32) NOT NULL,
  ns_aliases JSON NOT NULL,
  ns_core INT DEFAULT 0 NOT NULL,
  ns_additional JSON NOT NULL,
  UNIQUE INDEX uniquens (ns_dbname, ns_namespace_id),
  INDEX ns_dbname (ns_dbname)
) /*$wgDBTableOptions*/;
